# Generated by Django 4.1.3 on 2023-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thredsapi', '0004_alter_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
    ]
