# Generated by Django 4.1.3 on 2023-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thredsapi', '0006_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
